# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:25
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(default='FL', max_length=2, verbose_name='State'),
        ),
    ]
