# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20171117_0009'),
        ('addresses', '0002_auto_20171123_1125'),
    ]

    operations = [
    ]
