# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0002_creditcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='expdate',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expdate_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expdate_year',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2017),
        ),
    ]
