# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0003_auto_20171104_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expdate_year',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2017),
        ),
    ]
