# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0004_auto_20171115_1920'),
        ('creditcards', '0004_auto_20171113_1315'),
    ]

    operations = [
    ]
