# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0004_auto_20171119_1441'),
        ('creditcards', '0005_merge_20171116_1800'),
    ]

    operations = [
    ]
