# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171012_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(
                blank=True,
                default='',
                max_length=30,
                verbose_name='Nick name'), ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='user',
                serialize=False,
                to=settings.AUTH_USER_MODEL), ),
    ]
