# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user', ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart', ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item', ),
        migrations.RemoveField(
            model_name='saveditem',
            name='cart', ),
        migrations.RemoveField(
            model_name='saveditem',
            name='item', ),
        migrations.DeleteModel(name='Cart', ),
        migrations.DeleteModel(name='CartItem', ),
        migrations.DeleteModel(name='SavedItem', ),
    ]
