# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_auto_20171028_0335'),
        ('carts', '0002_auto_20171030_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
